### ISSUE TITLE
master_adapter and slave_adapter

### ISSUE THREAD

**Issue by Lien-NGSdummie** [mikessh/mageri#34]
Hi Mikhail, 

I really enjoyed reading your Mageri paper, and it seems like a super useful tool. However, I have a practical question regarding the use of the master_adapter and slave_adapter. I would like to see a real example, so that I know more exactly what the adapters should look like. Do you only use a master_adapter with single end reads? Or when can you omit the slave_adapter? What does the master_first column mean exactly?

I have attached an example of one of my setups on which I would like to use your Mageri tool: 
![truseq adapters with umi](https://user-images.githubusercontent.com/33087608/31992428-99005e9a-b97a-11e7-969e-f30195514b34.jpg). The starting point are TruSeq adapters where we added one UMI. Samples are pooled and will be sequenced using paired-end Illumina Next-Seq chemistry. 

Could you maybe point out some tips and tricks on how to set up the adapter sequences for Mageri? 

Thanks a lot.

**Comment by mikessh** [comment]
Hello, thanks for your feedback!

The master/slave_adapter follow are similar to what we've introduced in our MIGEC software. Basically the paired end read is first scanned for master, if there is a master adapter match then if slave sequence is provided it is searched and used for verification of master/extracting additional UMI letters. Note that the MIGEC software is mostly focused on RT-PCR designs, when N bases are found in the 5' adapter.

One should always provide the master adapter for both single- and paired-end sequencing (if it is in read#2 the paired end read will be re-oriented). Slave adapter is optional. If your library prep includes additional adapter/primer for paired-end barcoding (helps to fight chimeras) or additional UMI bases you can include it.

Master_first means that your reads are oriented, i.e. the master adapter should be in first read and is in the same strand as the first read.

Unfortunately, as I'm not that good with library prep (I'm a bioinformatician who just happen to know the library designs that are commonly used in our lab), its hard for me to say what strategy you should follow without seeing the actual reads. If the Illumina index barcodes are trimmed, and you don't have the NNN... region in your reads (but somewhere else), the only option for you would be to concatenate these sequences and append them to you read header as UMI:NNNN:QQQQ (see http://mageri.readthedocs.io/en/latest/body.html#header-m4 option).

If it doesn't work for you, perhaps I can help more if you'll provide a couple of paired-end reads in FASTQ format with corresponding markup (adapter/primer/umi/etc).
