### ISSUE TITLE
How to remove cap on Q score

### ISSUE THREAD

**Issue by xuchang116** [mikessh/mageri#36]
The variant calling Q score is capped at 100. Is there any options to relax or remove this cap? Currently it won't differentiate 0.1% and 1% variants -- both are given a QUAL = 100. Thank you!

**Comment by mikessh** [comment]
Hello. Unfortunately, I don't think it is feasible to remove this cap, for the following reasons:

1) The QUAL score should not differentiate between 0.1% and 1% variants, it should just tell how likely a variant is called in error. Variant frequency is related to the effect size, while QUAL is related to P-value, so they are not the same things, both of them should be used in filtering.
2) More practical. Q100 means P<10^-10, computed using cumulative probability of a Beta-Binomial distribution. Lower values will result in possible inaccuracies related to floating-point arithmetic when computing cumulative distribution in cases of high coverage, etc.

**Comment by xuchang116** [comment]
Thank you for the response. In my data a 0.1% variant, although called by MAGERI, is likely a false positive. But a 1% variant is more likely to be real. That's why I want higher resolution in QUAL > 100 to distinguish the two cases. Are there any other metrics reported in the output files that can be useful for this purpose?

**Comment by mikessh** [comment]
I would just plot variant frequency vs QUAL, perhaps you can distinguish good variants from this.
