### ISSUE TITLE
Building Index Hung?

### ISSUE THREAD

**Issue by ccario83** [mikessh/mageri#37]
I've just started using `mageri` and love the idea of an end-to-end UMI variant analysis tool. However, I'm having trouble trying to get it work with a sample containing 70M paired reads. This is a cfDNA sample processed with the Rubicon TagSeq kit ([page 25 for UMI info](http://rubicongenomics.com/wp-content/uploads/2016/08/QAM-328-001-ThruPLEX-Tag-seq-Kit-Instruction-Manual.pdf)) and sequenced on an Illumina NovaSeq using PE150. The UMIs are the first 6 bases of R1 and the last 6 of R2 of each read. 

I used the following command to run mageri:
```Shell 
time java -Xms54G -Xmx240G -XX:ParallelGCThreads=4 -jar mageri.jar -M3 NNNNNN:NNNNNN --references ucsc.hg19.fasta -R1 S026-R1.fastq.gz -R2 S026-R2.fastq.gz out/
```

After running for about 20 hours, `mageri` looks to be about 52M/70M or 74% done indexing, but progress has slowed to a halt as **in the last 2 hours it has only processed 8 reads**:
```
[Mon Mar 26 23:50:33 PDT 2018 +467m46s] [Indexer] Building UMI index, 52658259 reads processed, 99.99% extracted..
[Mon Mar 26 23:54:43 PDT 2018 +471m56s] [Indexer] Building UMI index, 52658260 reads processed, 100.0% extracted..
[Tue Mar 27 00:07:03 PDT 2018 +484m16s] [Indexer] Building UMI index, 52658267 reads processed, 100.0% extracted..
[Tue Mar 27 00:35:31 PDT 2018 +512m44s] [Indexer] Building UMI index, 52658277 reads processed, 100.0% extracted..
[Tue Mar 27 00:51:27 PDT 2018 +528m40s] [Indexer] Building UMI index, 52658280 reads processed, 100.0% extracted..
[Tue Mar 27 01:24:00 PDT 2018 +561m13s] [Indexer] Building UMI index, 52658285 reads processed, 99.99% extracted..
[Tue Mar 27 02:25:20 PDT 2018 +622m33s] [Indexer] Building UMI index, 52658287 reads processed, 100.0% extracted..
[Tue Mar 27 04:52:50 PDT 2018 +770m03s] [Indexer] Building UMI index, 52658292 reads processed, 100.0% extracted..
[Tue Mar 27 05:44:30 PDT 2018 +821m43s] [Indexer] Building UMI index, 52658297 reads processed, 100.0% extracted..
[Tue Mar 27 08:06:46 PDT 2018 +963m59s] [Indexer] Building UMI index, 52658306 reads processed, 100.0% extracted..
[Tue Mar 27 09:36:28 PDT 2018 +1053m41s] [Indexer] Building UMI index, 52658315 reads processed, 99.99% extracted..
[Tue Mar 27 11:41:53 PDT 2018 +1179m06s] [Indexer] Building UMI index, 52658323 reads processed, 99.99% extracted..
```
Of the 240Gb of RAM given, its currently only using about 107Gb.

I'm not sure I'm interpreting the output correctly and if this is to be expected, so I thought I'd ask. Is this normal? About how long should a sample of this size take to run? Any help is greatly appreciated!

**Comment by mikessh** [comment]
Hello!

To debug this issue, the simplest way would be to process first N (say 1-10mln reads, use ``--limit 10000000``) and look at the resulting summary files (checkout/umi histogram/assemble).

It is possible that the UMI position may be different (not first/last 6 bases) in your case, resulting in too large read groups (MIGs) being formed and corresponding performance issues.

You can also try to shift your UMI tags, say ``-M3 nnNNNNNN:NNNNNNnn`` as first two bases of the "stem" appear to be random as well.

**Comment by ccario83** [comment]
Thanks for the idea. I still run into similar memory issues, even when limiting to just 10 reads, so I'm not sure what to try next:

```Shell
time java -Xms32G -jar mageri.jar -M3 nnNNNN:NNNNnn --references ucsc.hg19.fasta --limit 10 -R1 S026-R1.fastq.gz -R2 S026-R2.fastq.gz out/
```

```Shell
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3284)
	at com.milaboratory.util.IntArrayList.ensureCapacity(IntArrayList.java:64)
	at com.milaboratory.util.IntArrayList.add(IntArrayList.java:69)
	at com.antigenomics.mageri.core.mapping.kmer.KmerMap.increment(KmerMap.java:221)
	at com.antigenomics.mageri.core.mapping.kmer.KmerUtils.countKmers(KmerUtils.java:83)
	at com.antigenomics.mageri.core.mapping.kmer.KmerUtils.buildKmerMap(KmerUtils.java:113)
	at com.antigenomics.mageri.core.mapping.kmer.KMerFinder.<init>(KMerFinder.java:39)
	at com.antigenomics.mageri.core.mapping.alignment.ExtendedKmerAlignerFactory.<init>(ExtendedKmerAlignerFactory.java:32)
	at com.antigenomics.mageri.core.mapping.alignment.ExtendedKmerAlignerFactory.<init>(ExtendedKmerAlignerFactory.java:28)
	at com.antigenomics.mageri.pipeline.analysis.ProjectAnalysis.<init>(ProjectAnalysis.java:81)
	at com.antigenomics.mageri.pipeline.Mageri.main(Mageri.java:121)
java -Xms32G -jar mageri.jar -M3 nnNNNN:NNNNnn --references  --limit 10 -R1    4722.61s user 184.66s system 252% cpu 32:25.62 total
```

How many distinct UMIs can mageri deal with? Is there a sample file of fastq UMI reads generated from cfDNA that I could compare against?

**Comment by mikessh** [comment]
I think that for the last issue it is the number of target regions, not the UMIs that are causing the problem, as MAGERI was not designed for WGS. You can try to limit yourself to the exome (i.e. specifying the reference fasta file containing exon sequences) -- this should fix your problem.

**Comment by ccario83** [comment]
Ah, thanks for the help! I'll give it a go with a reduced dataset.

**Comment by ccario83** [comment]
Awesome, it works now. Thanks for the help, impressive software!
